name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 16 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {
      branches: ["master", "main"],
      # ÈÖçÁΩÆÊñá‰ª∂Êõ¥Êñ∞Êó∂Ëß¶Âèë
      paths: [".github/workflows/metrics.yaml"],
    }

jobs:
  snk:
    name: Generate Snake SVG
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # https://github.com/Platane/snk
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: image/README/github-snake.svg

  # https://github.com/lowlighter/metrics
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: ü¶ë General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: image/README/general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          # output_action: gist
          # committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, tex, less, makefile, qmake, lex, cmake, gnuplot, scala, ejs, c, js
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 30
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/topics/README.md
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes

      # https://github.com/lowlighter/metrics/blob/master/source/plugins/leetcode/README.md
      - name: 3rd platform
        uses: lowlighter/metrics@latest
        with:
          # filename: metrics.plugin.leetcode.svg
          # filename: metrics.plugin.wakatime.svg
          filename: image/README/metrics.plugin.3rd.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/wakatime/README.md
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
